<%@ Page Title="" Language="C#" MasterPageFile="~/master.Master" AutoEventWireup="true" CodeBehind="addproduct.aspx.cs" Inherits="OSPS.WebForm2" %>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

  
    <form id="form1" runat="server" style="margin-top: 80px">

  
    <table cellpadding="6" cellspacing="4" class="nav-justified" style="height: 314px; width: 104%;">
        <tr>
            <td colspan="2">
                <table cellpadding="8" cellspacing="8" class="nav-justified" style="width: 60%; height: 255px;">
                    <tr>
                        <td style="width: 132px; color: #0066FF; font-size: medium; height: 31px;"><strong>Product Name:</strong></td>
                        <td style="width: 173px; height: 31px">
                            <strong>
                            <asp:TextBox ID="TextBox1" runat="server" Width="205px" style="font-size: medium"></asp:TextBox>
                            </strong>
                        </td>
                    </tr>
                    <tr>
                        <td style="width: 132px; color: #0066FF; font-size: medium; height: 32px;"><strong>Product Price:</strong></td>
                        <td style="width: 173px; height: 32px">
                            <strong>
                            <asp:TextBox ID="TextBox2" runat="server" Width="205px" style="font-size: medium"></asp:TextBox>
                            </strong>
                        </td>
                    </tr>
                    <tr>
                        <td style="width: 132px; color: #0066FF; font-size: medium; height: 32px;"><strong>Brand:</strong></td>
                        <td style="width: 173px; height: 32px">
                            <strong>
                            <asp:TextBox ID="TextBox3" runat="server" Width="205px" style="font-size: medium"></asp:TextBox>
                            </strong>
                        </td>
                    </tr>
                    <tr>
                        <td style="width: 132px; color: #0066FF; font-size: medium; height: 32px;"><strong>Quantuty:</strong></td>
                        <td style="width: 173px; height: 32px">
                            <strong>
                            <asp:TextBox ID="TextBox4" runat="server" Width="205px" style="font-size: medium"></asp:TextBox>
                            </strong>
                        </td>
                    </tr>
                    <tr>
                        <td style="width: 132px; color: #0066FF; font-size: medium; height: 32px;"><strong>Description:</strong></td>
                        <td style="width: 173px; height: 32px">
                            <strong>
                            <asp:TextBox ID="TextBox5" runat="server" Width="205px" style="font-size: medium"></asp:TextBox>
                            </strong>
                        </td>
                    </tr>
                    <tr>
                        <td style="width: 132px; font-size: medium; height: 32px;"><span style="color: #0066FF; font-size: medium;"><strong>Image Link:</strong></span></td>
                        <td style="width: 173px; height: 32px">
                            <asp:FileUpload ID="FileUpload1" runat="server" Width="205px" />
                        </td>
                    </tr>
                    <tr>
                        <td style="width: 132px; font-size: medium; height: 32px;">&nbsp;</td>
                        <td style="width: 173px; height: 32px">&nbsp;</td>
                    </tr>
                    <tr>
                        <td style="width: 132px; height: 32px;">
                            <asp:Label id="l3" Text="" runat="server"></asp:Label>
                        </td>
                        <td class="text-right" style="width: 173px; height: 32px">
                            <asp:Button ID="Button1" runat="server" OnClick="Button1_Click1" Text="ADD" Width="94px" />
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr>
            <td style="width: 680px" class="modal-lg">&nbsp;</td>
            <td style="width: 306px">&nbsp;</td>
        </tr>
        <tr>
                          <span>
                            
                               
            <td  valign="top" colspan="2">
                <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" BackColor="White" BorderColor="#CCCCCC" BorderStyle="None" BorderWidth="1px" CellPadding="3" DataKeyNames="Name" DataSourceID="SqlDataSource2" Height="215px" Width="833px" AllowSorting="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
                    <Columns>
                        <asp:BoundField DataField="Name" HeaderText="Name" ReadOnly="True" SortExpression="Name" />
                        <asp:BoundField DataField="Brand" HeaderText="Brand" SortExpression="Brand" />
                        <asp:BoundField DataField="Price" HeaderText="Price" SortExpression="Price" />
                        <asp:BoundField DataField="Quantity" HeaderText="Quantity" SortExpression="Quantity" />
                        <asp:BoundField DataField="Description" HeaderText="Description" SortExpression="Description" />
                        <asp:BoundField DataField="Image" HeaderText="Image" SortExpression="Image" />
                    </Columns>
                    <FooterStyle BackColor="White" ForeColor="#000066" />
                    <HeaderStyle BackColor="#006699" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="White" ForeColor="#000066" HorizontalAlign="Left" />
                    <RowStyle ForeColor="#000066" />
                    <SelectedRowStyle BackColor="#669999" Font-Bold="True" ForeColor="White" />
                    <SortedAscendingCellStyle BackColor="#F1F1F1" />
                    <SortedAscendingHeaderStyle BackColor="#007DBB" />
                    <SortedDescendingCellStyle BackColor="#CAC9C9" />
                    <SortedDescendingHeaderStyle BackColor="#00547E" />
                </asp:GridView>
                <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" SelectCommand="SELECT * FROM [PTable]" UpdateCommand="UPDATE [PTable] SET [Brand]=@Brand,[Price]=@Price,[Quantity]=@Quantity,[Description]=@Description,[Image]=@Image Where [Name]=@Name" DeleteCommand="DELETE from [PTable] Where [Name]=@Name "></asp:SqlDataSource>
            </td>
                               
                               
                          </span>
        </tr>
    </table>

  
</form>

  
</asp:Content>
