<%@ Page Title="" Language="C#" MasterPageFile="~/master.Master" AutoEventWireup="true" CodeBehind="Promotion.aspx.cs" Inherits="OSPS.WebForm4" %>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

    <form id="form1" runat="server">
    <table class="nav-justified" style="height: 254px">
        <tr>
            <td style="width: 498px">
                <table style="width: 77%; border-collapse: collapse">
                    <tr>
                        <td valign="top" colspan="2" style="font-size: large"><strong>PROMOTION PRODUCT</strong></td>
                    </tr>
                    <tr>
                        <td class="modal-sm" style="width: 141px; height: 19px;"></td>
                        <td style="height: 19px"></td>
                    </tr>
                    <tr>
                        <td class="modal-sm" style="width: 141px; height: 13px;">Product Name:</td>
                        <td style="height: 13px">
                            <asp:TextBox ID="TextBox1" runat="server" Width="222px"></asp:TextBox>
                        </td>
                    </tr>
                    <tr>
                        <td class="modal-sm" style="width: 141px">Product Image:</td>
                        <td>
                            <asp:FileUpload ID="FileUpload1" runat="server" />
                        </td>
                    </tr>
                    <tr>
                        <td class="modal-sm" style="width: 141px">&nbsp;</td>
                        <td>&nbsp;</td>
                    </tr>
                    <tr>
                        <td class="modal-sm" style="width: 141px">&nbsp;</td>
                        <td class="text-right">
                            <asp:Button ID="Button1" runat="server" Text="ADD" Width="84px" OnClick="Button1_Click" />
                        </td>
                    </tr>
                </table>
            </td>
            <td valign="top" >
                <table class="nav-justified" style="height: 48px">
                    <tr>
                        <td colspan="2" style="font-size: large"><strong>PROMOTIONAL PRODUCT tABLE</strong></td>
                    </tr>
                    <tr>
                        <td style="width: 272px">
                            <asp:GridView ID="GridView1" runat="server" Width="313px" AutoGenerateColumns="False" BackColor="White" BorderColor="#3366CC" BorderStyle="None" BorderWidth="1px" CellPadding="4" DataKeyNames="Name" DataSourceID="SqlDataSource1" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
                                <Columns>
                                    <asp:BoundField DataField="Name" HeaderText="Name" ReadOnly="True" SortExpression="Name" />
                                    <asp:BoundField DataField="Image" HeaderText="Image" SortExpression="Image" />
                                </Columns>
                                <FooterStyle BackColor="#99CCCC" ForeColor="#003399" />
                                <HeaderStyle BackColor="#003399" Font-Bold="True" ForeColor="#CCCCFF" />
                                <PagerStyle BackColor="#99CCCC" ForeColor="#003399" HorizontalAlign="Left" />
                                <RowStyle BackColor="White" ForeColor="#003399" />
                                <SelectedRowStyle BackColor="#009999" Font-Bold="True" ForeColor="#CCFF99" />
                                <SortedAscendingCellStyle BackColor="#EDF6F6" />
                                <SortedAscendingHeaderStyle BackColor="#0D4AC4" />
                                <SortedDescendingCellStyle BackColor="#D6DFDF" />
                                <SortedDescendingHeaderStyle BackColor="#002876" />
                            </asp:GridView>
                            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" SelectCommand="SELECT * FROM [Promotion]" UpdateCommand="UPDATE [Promotion] SET [Image]=@Image Where [Name]=@Name" DeleteCommand="DELETE from [Promotion] Where [Name]=@Name " ></asp:SqlDataSource>
                        </td>
                        <td>&nbsp;</td>
                    </tr>
                </table>
            </td>
        </tr>
        </table>
        <table class="nav-justified">
            <tr>
                <td colspan="2" style="font-size: large"><strong>NEW ARRIVAL</strong></td>
                <td style="font-size: large; width: 676px;" class="modal-sm">&nbsp;</td>
                <td style="font-size: large"><strong>NEW ARRIVAL PRODUCT TABLE</strong></td>
            </tr>
            <tr>
                <td style="width: 153px">&nbsp;</td>
                <td class="modal-sm" style="width: 320px">&nbsp;</td>
                <td class="modal-sm" style="width: 676px">&nbsp;</td>
                <td style="width: 474px">&nbsp;</td>
            </tr>
            <tr>
                <td style="width: 153px; height: 40px">Name:</td>
                <td class="modal-sm" style="height: 40px; width: 320px">
                    <asp:TextBox ID="TextBox2" runat="server" Width="222px"></asp:TextBox>
                </td>
                <td class="modal-sm" style="height: 40px; width: 676px">
                    &nbsp;</td>
                <td rowspan="5" style="width: 474px">
                    <asp:GridView ID="GridView2" runat="server" AutoGenerateColumns="False" BackColor="White" BorderColor="#3366CC" BorderStyle="None" BorderWidth="1px" CellPadding="4" DataKeyNames="Name" DataSourceID="SqlDataSource2" Width="380px" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
                        <Columns>
                            <asp:BoundField DataField="Name" HeaderText="Name" ReadOnly="True" SortExpression="Name" />
                            <asp:BoundField DataField="Price" HeaderText="Price" SortExpression="Price" />
                            <asp:BoundField DataField="Image" HeaderText="Image" SortExpression="Image" />
                        </Columns>
                        <FooterStyle BackColor="#99CCCC" ForeColor="#003399" />
                        <HeaderStyle BackColor="#003399" Font-Bold="True" ForeColor="#CCCCFF" />
                        <PagerStyle BackColor="#99CCCC" ForeColor="#003399" HorizontalAlign="Left" />
                        <RowStyle BackColor="White" ForeColor="#003399" />
                        <SelectedRowStyle BackColor="#009999" Font-Bold="True" ForeColor="#CCFF99" />
                        <SortedAscendingCellStyle BackColor="#EDF6F6" />
                        <SortedAscendingHeaderStyle BackColor="#0D4AC4" />
                        <SortedDescendingCellStyle BackColor="#D6DFDF" />
                        <SortedDescendingHeaderStyle BackColor="#002876" />
                    </asp:GridView>
                    <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" SelectCommand="SELECT * FROM [NewArrival]" UpdateCommand="UPDATE [NewArrival] SET [Price]=@Price,[Image]=@Image Where [Name]=@Name" DeleteCommand="DELETE from [NewArrival] Where [Name]=@Name "></asp:SqlDataSource>
                </td>
            </tr>
            <tr>
                <td style="width: 153px">Price:</td>
                <td class="modal-sm" style="width: 320px">
                    <asp:TextBox ID="TextBox3" runat="server" Width="222px"></asp:TextBox>
                </td>
                <td class="modal-sm" style="width: 676px">
                    &nbsp;</td>
            </tr>
            <tr>
                <td style="width: 153px; height: 36px">Image:</td>
                <td class="modal-sm" style="width: 320px; height: 36px">
                    <asp:FileUpload ID="FileUpload2" runat="server" />
                </td>
                <td class="modal-sm" style="width: 676px; height: 36px">
                    &nbsp;</td>
            </tr>
            <tr>
                <td style="width: 153px">&nbsp;</td>
                <td class="modal-sm" style="width: 320px">&nbsp;</td>
                <td class="modal-sm" style="width: 676px">&nbsp;</td>
            </tr>
            <tr>
                <td style="width: 153px">&nbsp;</td>
                <td class="modal-sm" style="text-align: right; width: 320px">
                    <asp:Button ID="Button2" runat="server" OnClick="Button2_Click" Text="ADD" Width="92px" />
                </td>
                <td class="modal-sm" style="text-align: right; width: 676px">
                    &nbsp;</td>
            </tr>
        </table>
        <table class="nav-justified" style="height: 254px">
        <tr>
            <td valign="top" style="width: 498px">&nbsp;</td>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <td style="width: 498px">&nbsp;</td>
            <td>&nbsp;</td>
        </tr>
        </table>
</form>

</asp:Content>
